Fix `origin` argument for burn() and burn_all() benchmarks to avoid errors
RawOrigin::Root yields errors:
Error: Input("Benchmark pallet_creditcoin::burn_all failed: Bad origin")
Error: Input("Benchmark pallet_creditcoin::burn failed: Bad origin")

because the extrinsic signature is checked like so::

	let who = ensure_signed(origin)?;

RawOrigin::Root should be used when the extrinsic signature check is::

	ensure_root(origin)?;

See for example set_gate_faucet()!