Allow actions-rs/grcov to fail
because recently it started failing with:

  Error: failed to compile `grcov v0.8.19`, intermediate artifacts can be found at `/var/folders/h1/8hndypj13nsbj5pn4xsnv1tm0000gn/T/cargo-installyBLQUt`
  Caused by:
    package `clap_lex v0.7.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0-nightly
    Try re-running cargo install with `--locked`

and this actions doesn't allow control over how `cargo install` is
executed internally