Fix `balance` argument for burn() benchmark to avoid errors
NOTE: always use a multiple of the existential deposit because
make_free_balance_be() checks that, see
https://paritytech.github.io/polkadot-sdk/master/src/pallet_balances/impl_currency.rs.html#476

The reason we were getting the error:
Error: Input("Benchmark pallet_creditcoin::burn failed: BurnInsufficientFunds")

is that MIN is 500 and the original chosen value of 100 is lower which
causes the check above to fail.

WARNING: the values `100` and `500` are in CREDO, not in CTC. That is
10^-18 CTC!