Skip Checkov warnings around EncryptionAtHost for Azure VMs
because this feaature isn't enabled on our subscription, see
https://github.com/gluwa/creditcoin/actions/runs/6717567205/job/18255654680?pr=1390

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/3d91f14a-f591-496b-a3d1-f198b84caaa3/resourceGroups/github-runner-6717567205-attempt-1/providers/Microsoft.Resources/deployments/runner","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","target":"securityProfile.encryptionAtHost","message":"The property 'securityProfile.encryptionAtHost' is not valid because the 'Microsoft.Compute/EncryptionAtHost' feature is not enabled for this subscription."}]}}